version: '3.5'
services:
  nginx: 
    image: harbor.lnxsystems.com/library/frontend:1.19-0.0.1
    container_name: frontned_nginx
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - djprojnet
      - nettest
    dns_search: .

  django_backend:
    image: harbor.lnxsystems.com/library/django:0.0.1
    container_name: djproj
    networks:
      - djprojnet


networks:
  djprojnet: {}
  nettest: 
    driver: bridge
